// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MyShopsAPI.Persistence;
using System;

namespace MyShopsAPI.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20171001082653_initialModel")]
    partial class initialModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyShopsAPI.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FeedbackDate");

                    b.Property<string>("Name")
                        .HasMaxLength(255);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(255);

                    b.Property<int>("Rating");

                    b.Property<bool>("RequiresCall");

                    b.Property<int>("ServiceType");

                    b.Property<string>("StoreName")
                        .HasMaxLength(255);

                    b.Property<DateTime>("VisitDate");

                    b.HasKey("Id");

                    b.ToTable("FeedBacks");
                });

            modelBuilder.Entity("MyShopsAPI.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("FridayClose")
                        .HasMaxLength(255);

                    b.Property<string>("FridayOpen")
                        .HasMaxLength(255);

                    b.Property<string>("Image");

                    b.Property<string>("MondayClose")
                        .HasMaxLength(255);

                    b.Property<string>("MondayOpen")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("SaturdayClose")
                        .HasMaxLength(255);

                    b.Property<string>("SaturdayOpen")
                        .HasMaxLength(255);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("SundayClose")
                        .HasMaxLength(255);

                    b.Property<string>("SundayOpen")
                        .HasMaxLength(255);

                    b.Property<string>("ThursdayClose")
                        .HasMaxLength(255);

                    b.Property<string>("ThursdayOpen")
                        .HasMaxLength(255);

                    b.Property<string>("TuesdayClose")
                        .HasMaxLength(255);

                    b.Property<string>("TuesdayOpen")
                        .HasMaxLength(255);

                    b.Property<string>("WednesdayClose")
                        .HasMaxLength(255);

                    b.Property<string>("WednesdayOpen")
                        .HasMaxLength(255);

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Shops");
                });
#pragma warning restore 612, 618
        }
    }
}
